[package]
name = "ele_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
serialport = "4"
image = "0.24"
chrono = "0.4"
rand = "0.8"
anyhow = "1.0"
log = "0.4"
simplelog = "0.12"