[package]
name = "ele_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
rand = "0.10.0"
anyhow = "1.0"
log = "0.4"
simplelog = "0.12"

# ElectronBot library (GitHub)
electron-bot = { git = "https://github.com/TOTHTOT/ElectronBotLib.git" }