[target.x86_64-pc-windows-msvc]
rustflags = ["-L", "native=./assets/module/vosk_win64_lib"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-L", "native=./assets/module/vosk_linux64_lib"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-L", "native=./assets/module/vosk_linux_arcch64_lib"]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH_aarch64_unknown_linux_gnu = "/usr/lib/aarch64-linux-gnu/pkgconfig/"